spring:
  application:
    name: chatapp
  data:
    mongodb:
      uri: mongodb+srv://talhaatif573:jTq7nZCY86JF8VYK@talha.x5yrf.mongodb.net/chatapp?retryWrites=true&w=majority&appName=Talha&ssl=true&connectTimeoutMS=30000&socketTimeoutMS=30000&serverSelectionTimeoutMS=50000&maxPoolSize=50&retryReads=true
      auto-index-creation: true

  messages:
    basename: i18n/messages

  web:
    resources:
      static-locations: classpath:/static/
    mvc:
      static-path-pattern: /**
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

server:
  port: 8080

logging:
  level:
    org.springframework.web: INFO
    org.springframework.data.mongodb.core: DEBUG
    com.talhaatif.chatapp: DEBUG
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always